[env:rak3312]
custom_meshtastic_hw_model = 106
custom_meshtastic_hw_model_slug = RAK3312
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 1
custom_meshtastic_display_name = RAK3312
custom_meshtastic_images = rak_3312.svg
custom_meshtastic_tags = RAK
custom_meshtastic_requires_dfu = false
custom_meshtastic_partition_scheme = 16MB
extends = esp32s3_base
board = wiscore_rak3312
board_level = pr
board_check = true
upload_protocol = esptool
build_src_filter =
  ${esp32s3_base.build_src_filter} +<mesh/eth/>
build_flags = 
  ${esp32s3_base.build_flags}
  -D RAK3312
  -I variants/esp32s3/rak3312
  -D HAS_ETHERNET=1
  -D W5100S_ETHERNET=1
  -D HAS_WIFI=0
  -D W5100_MAX_SOCK_NUM=1
  -D ETHERNET_LARGE_BUFFERS
lib_deps =
  ${esp32s3_base.lib_deps}
  ${networking_base.lib_deps}
  ${networking_extra.lib_deps}
  https://github.com/RAKWireless/RAK13800-W5100S/archive/1.0.2.zip

[env:rak3112]
extends = esp32s3_base
board = wiscore_rak3312
board_level = extra
upload_protocol = esptool
build_src_filter =
  ${esp32s3_base.build_src_filter} +<mesh/eth/>
build_flags =
  ${esp32_base.build_flags}
  -D RAK3312 
  -D _VARIANT_RAK3112_
  -I variants/esp32s3/rak3312
  -D HAS_ETHERNET=1
  -D W5100S_ETHERNET=1
lib_deps =
  ${esp32s3_base.lib_deps}
  ${networking_base.lib_deps}
  ${networking_extra.lib_deps}
  https://github.com/RAKWireless/RAK13800-W5100S/archive/1.0.2.zip